# Name: OLAREWAJU ESTHER OLUWASEYI
# Matric Number: ANA/22/8769

# Question 2: Show the list of numbers that would be generated by each of the following range expansions

# (a) range(5)
print(list(range(5)))

# (b) range(3, 10)
print(list(range(3, 10)))

# (c) range(4, 13, 3)
print(list(range(4, 13, 3)))

# (d) range(15, 5, -2)
print(list(range(15, 5, -2)))

# (e) range(5, 3)
print(list(range(5, 3)))
 
# Question 3: Given the initial statements:
import string
s1 = "spam"
s2 = "ni!"
#Show the result of evaluating each of the following string expressions.

# (a) "The Knights who say, " + s2
result_a = "The Knights who say, " + s2
print(result_a)

# (b) 3 * s1 + 2 * s2
result_b = 3 * s1 + 2 * s2
print(result_b)

# (c) s1[1]
result_c = s1[1]
print(result_c)

# (d) s1[1:3]
result_d = s1[1:3]
print(result_d)

# (e) s1[2] + s2[:2]
result_e = s1[2] + s2[:2]
print(result_e)